sudo: false

language:
  - cpp

addons:
  sonarcloud:
    organization: "duxiaocheng"
    token:
      secure: "J8cSw6EABBVisruoq45sEEeV8TYzAW8SGAAJGwc+YwquPVkZiOVzdkj6XIOFQOChlZCZIgstuYjbL7QN2fYvvtHHPmE74N3gRPqP37cmmVXA6QdF/zJBVGwdFFLpgsXze95rNmK/YYljswajWLltFzF2omSmmG1+NSnW4NdHtWny1k65nYBwe68HTV3+OreSF3B+AB0MJ/xJ7+Sb8TGxmSAA4tw8kDVPH+8EXNIKDKNHEpUhLR+OCfA31ypn1w2aDdXIYe1YFvYWhuJRW1cdVHms2Cm/VoYvZh+II9Pol8fWX183d8LgUW41rIIdasGrP3rWG7I5NhOcuqK/pxcdt63cKiKqX5dZoJTWCwK15RGCfiqyesr7wyvQmNFlFx4jBi7TsJPu5Od9ngMRx1Bq82e5L1XueL7IdGPpZnGB20He50QUEnuaIkXSV0UhQTdlE/Z1RMG8CrSdwy4TZHvfXL6lnsrEKDiCzLy1kpMojQGHuyEIFNO7aKIo3HHwGcR7GKc1S2wjDVmQH7a2b1QtkuyoLdY9Nne1pbIdb/zvzUdu1YSlw0Br4dD+eYrdi9N+4eYnsE+2TlOLVdF4bo+k88ApLtoG/lY803cHlTuppdx5BrulLAbonsgx754w3MIopZMknQcWKRsTOTYp7aygK6M6nz+EWS7ZRw8s+jRZ/mM="

script:
  # Prepare the build system
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

notifications:
  email: false
